apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-app
  namespace: real-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-app
  template:
    metadata:
      labels:
        app: real-app
    spec:
      containers:
        - name: real-app
          image: marwanaf/real-app:test
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://adminuser:password123@mongo-nodeport-svc.default:27017/real-app?authSource=admin
            - name: NODE_ENV
              value: production
            - name: SECRET
              value: secret
          imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
